# **Arreglos**

En este ejercicio de manejo de arreglos y de estructuras básicas de programación, se quieren lograr los cinco pasos enumerados a continuación:
1. Crear una matriz inicial, A, de tamaño 10x10 (o algún otro entero n>=10) que tiene números enteros cualesquiera entre el 1 y el 100. Estos números se pueden repetir. 
2. La matriz A que has creado no puede contener ciertos números. Los valores prohibidos son: múltiplos de 5 y números primos. 
3. Además, en la matriz A se debe cumplir la siguiente condición: no puede haber valores contiguos que sumen un múltiplo de 10. No elimines manualmente los valores del inciso 2 y 3. Asignales un 0 mediante un proceso automático. 
4. Recorrer la matriz A; si sus números son menores a 50 (o algún valor de referencia m), entonces escribirlos en un nuevo arreglo B. En caso contrario, ubicarlos en otro arreglo nuevo, C. 
5. Ordenar B y C de menor a mayor. Recuerda que el rango de valores es entre 1 y 100 (no debe haber ceros en B y en C, aunque sí los haya en A después de tus modificaciones). 

In [22]:
import numpy as np

Creamos la matriz de tamaño n >=10

In [23]:
n = 10
A = np.random.randint(1, 101, size=(n, n))
print(A)

[[44 99 34 38 36 72 32  3 50 27]
 [90 77 82 22 43  6 88  7 35 26]
 [61 41 54 58 27 96 77 64 94 89]
 [65  8 24 37 54  5 73 46 99 32]
 [14 53 51 80 53 58 93 62  6 42]
 [ 5 99  9 43  6  1  4 80 40 33]
 [95 42 38 25 50 48 60 41 79  5]
 [ 3 87 18 47 26 39 78 49 23 24]
 [35 46 70 98  7 63  4 97 35 90]
 [71 20 19 44 68  3 41 62 43 57]]


Ahora modificamos la matriz

Por definicion un número es primo si y solo si es divisible entre 1 y si mismo, bajo esta definición el 1 no se considera un número primo dado que solo tiene un solo divisor el mismo, hago esta aclaración dada la ambiguedad matematica que esto pueda representar para fines practicos del algoritmo

In [24]:
def es_primo(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

Una vez creada la función creamos un bucle que recorra la matriz completa primero cambiando los numeros primos y los multiplos de 5, para posteriormente recorrer el renglon verificando suma de contiguos multiplos de 10, el orden se debe a que garanatiza que posteriormente a los cambios realizados la matriz no tenga ningun valor prohibido

In [25]:
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        if A[i, j] % 5 == 0 or es_primo(A[i, j]):
            A[i, j] = -1
    for k in range(A.shape[1]-1):
        if (A[i , k] + A[i, k + 1]) % 10 == 0:
            A[i, k] = -1
            A[i, k+1] = -1

print(A)

[[44 99 34 38 36 72 32 -1 -1 27]
 [-1 77 82 22 -1  6 88 -1 -1 26]
 [-1 -1 54 58 27 96 77 64 94 -1]
 [-1  8 24 -1 54 -1 -1 46 99 32]
 [14 -1 -1 -1 -1 58 93 62  6 42]
 [-1 99  9 -1  6  1  4 -1 -1 33]
 [-1 -1 -1 -1 -1 48 -1 -1 -1 -1]
 [-1 87 18 -1 26 39 78 49 -1 24]
 [-1 46 -1 98 -1 63  4 -1 -1 -1]
 [-1 -1 -1 44 68 -1 -1 62 -1 57]]


In [26]:
m = 50
B = A[np.logical_and(A < m, A > 0)]
C = A[A >= m]
B.sort()
C.sort()

print(B)
print(C)

[ 1  4  4  6  6  6  8  9 14 18 22 24 24 26 26 27 27 32 32 33 34 36 38 39
 42 44 44 46 46 48 49]
[54 54 57 58 58 62 62 63 64 68 72 77 77 78 82 87 88 93 94 96 98 99 99 99]
